### ISSUE TITLE
Port to libsoup3

### ISSUE THREAD

**Issue by jbicha** [snapcore/snapd-glib#115]
snapd-glib needs to be ported to libsoup3 so that we can continue to use it with the GNOME 43 versions of 
- gnome-control-center
- gnome-initial-setup
- gnome-online-accounts
- gnome-software-plugin-snap (not used by the main Ubuntu Desktop, but used by Ubuntu Budgie and Xubuntu)

(It's not possible for apps to link against both libsoup2.4 and libsoup3 simultaneously)

I think you're going to need to keep a build option for libsoup2.4 since you may want new snapd-glib version to be usable by older distros.

- https://libsoup.org/libsoup-3.0/migrating-from-libsoup-2.html
- https://gitlab.gnome.org/GNOME/libsoup/-/issues/218

**Comment by jbicha** [comment]
I believe we can still build GNOME Software 43 against libsoup2.4 so this is mainly about keeping these other features working

- Snap integration with the Applications panel of the GNOME Settings app
- Snap login with GNOME Online Accounts
- Showing select Snaps (and links to them) in Initial Setup

**Comment by robert-ancell** [comment]
This will require us to take advantage of the [Unix socket support](https://gitlab.gnome.org/GNOME/libsoup/-/merge_requests/182) in libsoup3.

**Comment by jbicha** [comment]
@robert-ancell How is this going? Will this be available in time for Feature Freeze?

**Comment by robert-ancell** [comment]
It's more complex than I realized, I'm not sure how long it will take.

**Comment by robert-ancell** [comment]
I wasn't able to get it to work with the new libsoup3 unix support, but there is some in-progress code in https://github.com/robert-ancell/snapd-glib/tree/http-unix-session which might get used in the future.
