### ISSUE TITLE
pkgconfig file doesn't match where headers are installed

### ISSUE THREAD

**Issue by jbicha** [snapcore/snapd-glib#124]
- snapd-glib 1.61
- built with libsoup3

Header files are installed to `usr/include/snapd-glib-2/snapd-glib/`

But the pkgconfig file has

```
Libs: -L${libdir} -lsnapd-glib-2
Cflags: -I${includedir}/snapd-glib
```

These don't match.

**Comment by robert-ancell** [comment]
Fixed in 1.62
