### ISSUE TITLE
can't get all available snap packages

### ISSUE THREAD

**Issue by kledgeb** [snapcore/snapd-glib#13]
I'm using snapd_client_find_sync function to get all available snap packages for ubuntu desktop.
I'm setting "query" parameter to NULL and calling its function, because document says "query | query string to send or **NULL to find all**."

But following error is reported via error(GError) parameter.

domain : 1373
code : 10
message : cannot search: got unexpected HTTP status code 403 via GET to \"https://search.apps.ubuntu.com/api/v1/snaps/search?confinement=strict%2Cclassic&fields=anon_download_url%2Carchitecture%2Cchannel%2Cdownload_sha3_384%2Csummary%2Cdescription%2Cdeltas%2Cbinary_filesize%2Cdownload_url%2Cepoch%2Cicon_url%2Clast_updated%2Cpackage_name%2Cprices%2Cpublisher%2Cratings_average%2Crevision%2Cscreenshot_urls%2Csnap_id%2Csupport_url%2Ccontact%2Ctitle%2Ccontent%2Cversion%2Corigin%2Cdeveloper_id%2Cprivate%2Cconfinement%2Cchannel_maps_list&q=\"

System environment 

~$ snap --version
snap    2.26.14
snapd   2.26.14
series  16
ubuntu  17.04
kernel  4.10.0-32-generic

~$ apt-cache policy libsnapd-glib1
libsnapd-glib1:
  Installed: 1.13-0ubuntu0.17.04.1
  Candidate: 1.13-0ubuntu0.17.04.1
  Version table:
 *** 1.13-0ubuntu0.17.04.1 500
        500 http://archive.ubuntu.com/ubuntu zesty-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     1.9-0ubuntu1 500
        500 http://archive.ubuntu.com/ubuntu zesty/main amd64 Packages

Please let me know if needed information is missing.

BTW, I accessed above URL via borwser(Firefox) with removing last parameter "&q=" and then I could get JSON data and it looks like correct.

**Comment by robert-ancell** [comment]
The Ubuntu store changed its behaviour to no longer allow finding of all snaps. So I'll update the documentation in snapd-glib to reflect this.

**Comment by robert-ancell** [comment]
Fixed in dea59fa.

**Comment by kledgeb** [comment]
Thank you for your replay and works.
