### ISSUE TITLE
snapd-qt Qt6 port?

### ISSUE THREAD

**Issue by ScarlettGatelyMoore** [snapcore/snapd-glib#142]
Hello, we use snapd-qt in our store application Discover and our snap backend is not functional currently as we are moving to qt6. We need this ported to qt6!
Thanks,
Scarlett

**Comment by robert-ancell** [comment]
Sounds great - do you know anyone with Qt6 experience who could get this started?

**Comment by Conan-Kudo** [comment]
It'd be great to have this in place soon, Fedora KDE offers the snapd backend as an option and I would rather not have to remove it for the upgrade to Plasma 6 for Fedora Linux 40.

**Comment by ScarlettGatelyMoore** [comment]
I didn't get any hits in kde-devel, everyone is probably busy with there own ports. I will try to find some time and give it a shot.

**Comment by carlosdem** [comment]
https://github.com/snapcore/snapd-glib/pull/147
