### ISSUE TITLE
qt binding for installing snap with specific channel not working

### ISSUE THREAD

**Issue by soumyaDghosh** [snapcore/snapd-glib#154]
While working on the snap backend of discover, I was trying to implement the option that channels can be mentioned while installing. According to [this](https://github.com/snapcore/snapd-glib/blob/1.65/snapd-qt/Snapd/client.h#L1139), the channel just needs to be passed.

But, even with this, the snap is installed from `latest/stable` only

```clang
setRequest(m_client->install(app->packageName(), QStringLiteral("latest/edge")));
```
or
```clang
setRequest(m_client->install(app->packageName(), QStringLiteral("edge")));
````

**Comment by robert-ancell** [comment]
Is there a particular snap this is occurring with?

Some things to try:
- Compare with running the from the command line, e.g. `snap install --channel latest/edge <snap name>`
- Does the snap have that channel open? Use `snap info <snap name>` to check, it might be tracking the channel you chose but there is no snap in that channel.

**Comment by soumyaDghosh** [comment]
> Is there a particular snap this is occurring with?

Okay, thanks for this lead. It's probably working for only one particular snap. That snap is probably problematic. Thanks a lot for the quick reply! Closing!
