### ISSUE TITLE
Error in NEWS entries for snapd-glib

### ISSUE THREAD

**Issue by Conan-Kudo** [snapcore/snapd-glib#21]
For the NEWS entry for snapd-glib 1.22, you mentioned `liblightdm-qt`, which really has nothing to do with snapd-glib...

**Comment by Conan-Kudo** [comment]
You also mention for snapd-glib 1.17 that you reduced the `snapd-glib` dependency, but in fact you lowered the `json-glib` dependency...

**Comment by robert-ancell** [comment]
Muscle memory... Fixed in 619bd4f and 1228d92

**Comment by Conan-Kudo** [comment]
@robert-ancell Commits not pushed to GitHub. :)

**Comment by robert-ancell** [comment]
Aha, that would explain why the comment wasn't detecting these changes...
