### ISSUE TITLE
Getting information about a said snap

### ISSUE THREAD

**Issue by aleixpol** [snapcore/snapd-glib#30]
It would be useful to have an entry in the API that gave us information about a said snap much like `snap info` does.

At the moment the only way to check the installation state of a snap is to list installed files and see if it's there, which is convoluted and not really efficient.

This is also useful after installing when we need to make sure we know the installed size.

**Comment by robert-ancell** [comment]
info = snapd_client_list_one_sync (client, "moon-buggy", cancellable, &error);

will return the information about a locally installed snap (or an error if not installed).

info = snapd_client_find_sync (client, SNAPD_FIND_FLAGS_MATCH_NAME, "moon-buggy", NULL, cancellable, &error);

will return the store information for a snap. You can determine if it is installed with the results of the first call.
