### ISSUE TITLE
snapd-glib 1.32 fails to build in Fedora Rawhide (enforced no-undefined-symbols)

### ISSUE THREAD

**Issue by Conan-Kudo** [snapcore/snapd-glib#32]
I attempted to update to snapd-glib 1.32 in Fedora, and unfortunately it failed to build in Rawhide.

It breaks when it starts attempting to link libsnapd-qt due to a ton of undefined references. In Fedora, [we recently changed the flags such that builds fail when you try to link with undefined symbols](https://fedoraproject.org/wiki/Changes/BINUTILS2291#Scope). I do not see a reason for libsnapd-qt to have any undefined symbols against libsnapd-glib, or really anything else, so I'm not sure why this fails on this.

Sample build log: [snapd-glib-1.32-1.fc28.build.log.txt](https://github.com/snapcore/snapd-glib/files/1671757/snapd-glib-1.32-1.fc28.build.log.txt)

Koji scratch build (logs for all arches available): https://koji.fedoraproject.org/koji/taskinfo?taskID=24524309

**Comment by robert-ancell** [comment]
I have yet to try this in a VM but any pointers welcome... Guessing it's a linking order issue?

**Comment by Conan-Kudo** [comment]
Most likely.

**Comment by robert-ancell** [comment]
Can you recheck and see if it works now? I have it successfully compiling on Fedora and it now builds for both Ubuntu and Fedora in CI.

**Comment by Conan-Kudo** [comment]
We dropped adding `-Wl,--no-undefined` by default in Rawhide. I can force it to break again by switching it back on, though.

**Comment by Conan-Kudo** [comment]
@robert-ancell Also, if you want to specifically build against Rawhide, you'll need to pick `fedora:rawhide`, per https://store.docker.com/images/fedora

Note that rawhide probably needs updating regularly if you're pulling from Docker's official registry rather than Fedora's.

**Comment by robert-ancell** [comment]
Reproduced and fixed in cf3f9e0e02cf749499aa459e4419115f3cbfa5d0 by setting LDFLAGS before running configure, thanks!
