### ISSUE TITLE
libsoup-2.4 and json-glib-1.0 are installed, at versions newer than the minimum requirements, yet not found on Tumbleweed

### ISSUE THREAD

**Issue by fusion809** [snapcore/snapd-glib#35]
Hi,

I'm trying to build this package on Tumbleweed, and I get this configure error:

```bash
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/x86_64-suse-linux/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for
    glib-2.0 >= 2.46
    gio-2.0 >= 2.46
    gio-unix-2.0 >= 2.46
    libsoup-2.4 >= 2.32
    json-glib-1.0 >= 1.1.2
... no
configure: error: Package requirements (
    glib-2.0 >= 2.46
    gio-2.0 >= 2.46
    gio-unix-2.0 >= 2.46
    libsoup-2.4 >= 2.32
    json-glib-1.0 >= 1.1.2
) were not met:

No package 'libsoup-2.4' found
No package 'json-glib-1.0' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables SNAPD_CFLAGS
and SNAPD_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```

yet libsoup-2_4-1 is installed, specifically version 2.62.1, as is version libjson-glib-1_0-0 version 1.4.2. The content of these packages is:

```
/usr/lib64/libsoup-2.4.so.1
/usr/lib64/libsoup-2.4.so.1.8.0
/usr/lib64/libsoup-gnome-2.4.so.1
/usr/lib64/libsoup-gnome-2.4.so.1.8.0
/usr/share/doc/packages/libsoup-2_4-1
/usr/share/doc/packages/libsoup-2_4-1/NEWS
/usr/share/licenses/libsoup-2_4-1
/usr/share/licenses/libsoup-2_4-1/COPYING
```

and

```
/usr/lib64/libjson-glib-1.0.so.0
/usr/lib64/libjson-glib-1.0.so.0.400.2
/usr/share/licenses/libjson-glib-1_0-0
/usr/share/licenses/libjson-glib-1_0-0/COPYING
```

I have tried adjusting SNAPD_LIBS, to include /usr/lib64 in case /usr/lib64 isn't searched, that didn't work. But glib-2.0 is installed and detected, yet its libraries are in /usr/lib64 also, so it's not a problem with that directory not being searched. Can yas help?

Thanks for your time,
Brenton

**Comment by robert-ancell** [comment]
Are you missing the json-glib-devel and libsoup-devel packages? You have the libs, but I suspect not the development headers.

On Fedora, the following packages need to be installed:
`dnf install autoconf automake gcc gcc-c++ gobject-introspection-devel glib2-devel gtk-doc json-glib-devel libsoup-devel libtool make qt5-qtbase-devel qt5-qtdeclarative-devel vala`

**Comment by fusion809** [comment]
Yep you're so right, sorry I was missing them, can't believe I made such a trivial mistake.
