### ISSUE TITLE
Linking fails when using many parallel jobs

### ISSUE THREAD

**Issue by mati865** [snapcore/snapd-glib#50]
With `MAKEFLAGS` configured to use all cores building (this AUR package)[https://aur.archlinux.org/packages/snapd-glib] on Ryzen CPU fails with:
```
/usr/bin/ld: cannot find -lsnapd-qt
collect2: error: ld returned 1 exit status
libtool:   error: error: relink 'libSnapd.la' with the above command before installing it
```

**Comment by mati865** [comment]
Years ago issues like that were quite common when using too many jobs but nowadays they're very rare.

I forgot to mention it works with `-j1`. I've only last lines of the build log but I can reproduce it tomorrow.
With so many threads the build system tried to make a lot of libraries at same time and looks like one of them depends on snapd-qt which wasn't ready yet.

**Comment by mati865** [comment]
Yesterday it failed to build 4 times until I added `-j1` but today it doesn't fail no matter what.

I'll reopen issue if I experience the error again.

**Comment by robert-ancell** [comment]
This has spurred me to do the port to Meson (https://github.com/snapcore/snapd-glib/issues/33) - hopefully that will solve the issue or at least make it easier to debug.
